DROP TABLE IF EXISTS MTABLE;
DROP TABLE IF EXISTS MUSER;
DROP TABLE IF EXISTS FIELD;
DROP TABLE IF EXISTS NUMBER;
DROP SEQUENCE IF EXISTS TABLE_ID;
DROP SEQUENCE IF EXISTS USER_ID;
DROP SEQUENCE IF EXISTS FIELD_ID;
DROP SEQUENCE IF EXISTS NUMBER_ID;